version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: /app/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
