name: blog-actions
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blog-actions:latest

      - name: Deploy to NCP
        run: |
          echo "${{ secrets.NCP_SSH_KEY }}" > _temp_key
          chmod 600 _temp_key
          ssh -o StrictHostKeyChecking=no -i _temp_key ${{ secrets.NCP_SSH_USER }}@${{ secrets.NCP_SSH_HOST }} 'docker pull ${{ secrets.DOCKER_USERNAME }}/blog-actions:latest && docker-compose -f /home/docker/docker-compose.yml up -d'
          rm _temp_key
